name: popcornhub
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  http: ^1.3.0
  dartz: ^0.10.1
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  flutter_svg: ^2.0.17
  cached_network_image: ^3.4.1
  flutter_screenutil: ^5.9.3
  wiredash: ^2.4.0
  flutter_localizations:
    sdk: flutter
  youtube_player_flutter: ^9.1.1
  hive: ^2.2.3
  path_provider: ^2.1.5
  flare_flutter: ^3.0.2
  lottie: ^3.3.1
  simple_animations: ^5.1.0
  iconsax: ^0.0.8
  smooth_page_indicator: ^1.2.1


dev_dependencies: 
  hive_generator: ^2.0.1
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: "luncher_icon"
  ios: true
  image_path: "assets/icons/logo.png"


  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/pngs/
    - assets/languages/
    - assets/animations/
    - assets/demo/
    - assets/lottie/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
